import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import chalk from 'chalk';

export interface EnvVariable {
  name: string;
  description: string;
  required: boolean;
  secret: boolean;
  value?: string;
  source?: 'env' | 'dotenv' | 'user-input';
}

export interface PluginEnvRequirement {
  pluginName: string;
  variables: EnvVariable[];
}

export interface EnvAnalysisResult {
  requiredVariables: EnvVariable[];
  missingVariables: EnvVariable[];
  availableVariables: EnvVariable[];
  pluginRequirements: PluginEnvRequirement[];
  isComplete: boolean;
}

/**
 * Common environment variables required for Recall agents
 */
export const COMMON_ENV_VARIABLES: EnvVariable[] = [
  {
    name: 'OPENAI_API_KEY',
    description: 'API key for OpenAI services',
    required: false,
    secret: true
  },
  {
    name: 'ANTHROPIC_API_KEY',
    description: 'API key for Anthropic services',
    required: false,
    secret: true
  },
  {
    name: 'RECALL_PRIVATE_KEY',
    description: 'Private key for Recall network authentication',
    required: true,
    secret: true
  },
  {
    name: 'RECALL_BUCKET_NAME',
    description: 'Bucket name for storing agent data on Recall network',
    required: true,
    secret: false
  }
];

/**
 * Plugin-specific environment variables
 */
export const PLUGIN_ENV_REQUIREMENTS: Record<string, EnvVariable[]> = {
  // No hardcoded plugin environment variables
  // All plugin environment variables should be detected dynamically
};

/**
 * Analyze environment variables for a project
 */
export function analyzeEnvironment(
  projectPath: string, 
  installedPlugins: string[] = []
): EnvAnalysisResult {
  // Initialize result
  const result: EnvAnalysisResult = {
    requiredVariables: [...COMMON_ENV_VARIABLES],
    missingVariables: [],
    availableVariables: [],
    pluginRequirements: [],
    isComplete: false
  };

  // Add plugin-specific requirements
  for (const plugin of installedPlugins) {
    const envVars = PLUGIN_ENV_REQUIREMENTS[plugin];
    if (envVars) {
      result.requiredVariables.push(...envVars);
      result.pluginRequirements.push({
        pluginName: plugin,
        variables: envVars
      });
    }
  }

  // Get current environment variables
  const currentEnv = process.env;
  
  // Check for .env file
  const envPath = path.join(projectPath, '.env');
  let dotenvVars: Record<string, string> = {};
  
  if (fs.existsSync(envPath)) {
    try {
      const envConfig = dotenv.parse(fs.readFileSync(envPath));
      dotenvVars = envConfig;
    } catch (error) {
      console.warn(chalk.yellow(`Warning: Could not parse .env file at ${envPath}`));
    }
  }

  // Check each required variable
  for (const variable of result.requiredVariables) {
    // Look for the variable in the current environment or .env file
    const envValue = currentEnv[variable.name];
    const dotenvValue = dotenvVars[variable.name];
    
    if (envValue) {
      result.availableVariables.push({
        ...variable,
        value: envValue,
        source: 'env'
      });
    } else if (dotenvValue) {
      result.availableVariables.push({
        ...variable,
        value: dotenvValue,
        source: 'dotenv'
      });
    } else if (variable.required) {
      result.missingVariables.push(variable);
    }
  }

  // Check if we have all required variables
  result.isComplete = result.missingVariables.length === 0;

  return result;
}

/**
 * Generate an .env file from environment variables
 */
export function generateEnvFile(
  projectPath: string, 
  variables: EnvVariable[]
): { success: boolean; filePath: string; message?: string } {
  try {
    const envPath = path.join(projectPath, '.env');
    
    // Create content for .env file
    let content = '# Environment variables for Recall agent\n';
    content += '# Generated by recall-cli\n\n';
    
    for (const variable of variables) {
      if (variable.value) {
        content += `${variable.name}=${variable.value}\n`;
      }
    }
    
    // Write to file
    fs.writeFileSync(envPath, content, { encoding: 'utf8' });
    
    return {
      success: true,
      filePath: envPath
    };
  } catch (error) {
    return {
      success: false,
      filePath: path.join(projectPath, '.env'),
      message: error instanceof Error ? error.message : String(error)
    };
  }
}

/**
 * Extract environment variables from a file or directory
 */
export function extractEnvVariablesFromFiles(
  projectPath: string,
  pattern = /process\.env\.([A-Z_][A-Z0-9_]*)/g
): string[] {
  const result = new Set<string>();
  
  // Function to process a file
  function processFile(filePath: string) {
    if (!fs.existsSync(filePath) || !filePath.endsWith('.ts')) {
      return;
    }
    
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      let match;
      while ((match = pattern.exec(content)) !== null) {
        result.add(match[1]);
      }
    } catch (error) {
      console.warn(chalk.yellow(`Warning: Could not read file ${filePath}`));
    }
  }
  
  // Function to process a directory
  function processDirectory(dirPath: string) {
    const files = fs.readdirSync(dirPath, { withFileTypes: true });
    
    for (const file of files) {
      const fullPath = path.join(dirPath, file.name);
      
      if (file.isDirectory()) {
        processDirectory(fullPath);
      } else if (file.isFile() && file.name.endsWith('.ts')) {
        processFile(fullPath);
      }
    }
  }
  
  // Start processing
  processDirectory(projectPath);
  
  return Array.from(result);
} 